drop table if exists favorite_recipe cascade;
drop table if exists ingredients cascade;
drop table if exists recipe_embedding cascade;
drop table if exists recipes cascade;
drop table if exists users cascade;

create table recipes (
    created_at timestamp(6),
    id bigint generated by default as identity,
    updated_at timestamp(6),
    steps TEXT,
    title varchar(255) not null,
    primary key (id)
);

create table users (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    email varchar(255) unique,
    fullname varchar(255),
    image_url varchar(255),
    password varchar(255),
    provider varchar(255),
    role varchar(255),
    username varchar(255) unique,
    primary key (id)
);

create table favorite_recipe (
    recipe_id bigint not null,
    user_id bigint not null,
    primary key (recipe_id, user_id)
);

create table ingredients (
    id bigint generated by default as identity,
    recipe_id bigint,
    name TEXT,
    primary key (id)
);

-- H2 has no pgvector "vector" type; the real column is `vector(1536)` in production Postgres.
create table recipe_embedding (
    created_at timestamp(6),
    id bigint generated by default as identity,
    recipe_id bigint,
    embedding TEXT,
    primary key (id)
);

alter table if exists favorite_recipe add constraint FKk6h6tt52vcbo5qdkgtx7tahns foreign key (recipe_id) references recipes;
alter table if exists favorite_recipe add constraint FKmd21ehkkcaieh3885tt4n4xs5 foreign key (user_id) references users;
alter table if exists ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
